/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MyComponent,
} from './components/my-component/my-component';

export namespace Components {
  interface MyComponent {
    'currentRoll': number;
    'secondRoll': number;
    'winOrLose': string;
  }
  interface ResultComponent {
    'firstResult': number;
    'resultsOfRoll': MyComponent;
    'secondResult': number;
    'somethingHappens': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLResultComponentElement extends Components.ResultComponent, HTMLStencilElement {}
  var HTMLResultComponentElement: {
    prototype: HTMLResultComponentElement;
    new (): HTMLResultComponentElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'result-component': HTMLResultComponentElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    'currentRoll'?: number;
    'secondRoll'?: number;
    'winOrLose'?: string;
  }
  interface ResultComponent {
    'firstResult'?: number;
    'resultsOfRoll'?: MyComponent;
    'secondResult'?: number;
    'somethingHappens'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'result-component': ResultComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'result-component': LocalJSX.ResultComponent & JSXBase.HTMLAttributes<HTMLResultComponentElement>;
    }
  }
}


